### ISSUE TITLE
Svelte framework

### ISSUE THREAD

**Issue by jacmos3** [peterpeterparker/create-ic#12]
Hello, this is not a issue :) It just would be awesome if the there would be the option to start the project with a frontend setupped with Svelte in the frontend part selection

**Comment by peterpeterparker** [comment]
Thanks for the idea 👍

I actually do not plan to add such features to this CLI. It "just" aims to wrap dfx for npm and provide some support for useful canister such as internet identity.

Not sure if still maintained but, there is already a project that solves this https://github.com/MioQuispe/create-ic-app and the DFINITY examples repo provide some samples as well https://github.com/dfinity/examples/.

Note also that if you are looking to develop a frontend dapp with ease on the IC, you can check my main other project [Juno](https://juno.build). Kind of a little Firebase on Web3.

Again, thanks for the share!

**Comment by jacmos3** [comment]
thank you!
