### ISSUE TITLE
When deploying Frontend canister is not rendering my App.tsx file

### ISSUE THREAD

**Issue by ViktorArg** [peterpeterparker/create-ic#13]
Hello,
I created a project using this template, running all the commands in the readme, it seems to work fine but my frontend application is not rendering when deploying the frontend canister neither in local or ic, even though, npm start is rendering everything ok in http://localhost:3000/. It seems to be something with the config setting the canister id.

This is my frontend canister in the ic https://3ejf7-5iaaa-aaaal-qb3pq-cai.icp0.io/

Shows this error in the inspect Console:
dex.7930dc05.js:73 Uncaught ReferenceError: process is not defined
    at index.7930dc05.js:73:4407
(

Then going into the error:
canisterId = process.env.CANISTER_ID_BACKEND || "gn5qg-saaaa-aaaal-qbzia-cai" (It can't find this in the code)

I'm working in a pc windows with the wsl.

Thank you!

**Comment by peterpeterparker** [comment]
> I'm working in a pc windows with the wsl.

I guess your issue was the same as https://github.com/peterpeterparker/create-ic/issues/11 - i.e. the CLI currently does not supports Windows WSL
