### ISSUE TITLE
Error on deploying the empty project

### ISSUE THREAD

**Issue by jacmos3** [peterpeterparker/create-ic#9]
Hello, 
I'm trying to install a new project from zero using Create IC...
I cloned the Create IC project, 
then I ran the commands to create the new empty project and followed all the path for creating a new backend + frontend + IC project. 
Then I try to deploy the empty project using the command:
dfx deploy --no-wallet 

as suggested on the terminal by the tool, but it stucks with this error:

Installing canisters...
Creating UI canister on the local network.
The UI canister on the "local" network is "be2us-64aaa-aaaaa-qaabq-cai"
Installing code for canister internet_identity, with canister ID bnz7o-iuaaa-aaaaa-qaaaa-cai
Error: Failed while trying to deploy canisters.
Caused by: Failed while trying to deploy canisters.
  Failed while trying to install all canisters.
    Failed to install wasm module to canister 'internet_identity'.
      Failed during wasm installation call: The Replica returned an error: code 5, message: "Wasm module of canister bnz7o-iuaaa-aaaaa-qaaaa-cai is not valid: Failed to decode wasm module: unsupported canister module format"

I also tried to run dfx generate internet_identity for generating the candids, but still having the issue.

Do you know how to solve this?

It's on a MacBook pro with M1. 
dfx version 0.13 before and then upgraded to 0.14... still having the issue

Thanks

**Comment by peterpeterparker** [comment]
Thanks for the issue. I think I know what's the problem. Internet Identity pre-build development wasm is now provided as a `.wasm.gz` instead of plain `.wasm` and this cli was not updated accordignly. Let me fix that now.

**Comment by peterpeterparker** [comment]
Solved in #10.

To fix the project you already created, you can update the Internet Identity configuration in the `dfx.json` of your project as following:

```
"internet_identity": {
      "type": "custom",
      "candid": "https://github.com/dfinity/internet-identity/releases/latest/download/internet_identity.did",
      "wasm": "https://github.com/dfinity/internet-identity/releases/latest/download/internet_identity_dev.wasm.gz",
      "shrink": false,
      "remote": {
        "candid": "internet_identity.did",
        "id": {
          "ic": "rdmx6-jaaaa-aaaaa-aaadq-cai"
        }
      }
    }
```

if you want to start from scratch, you can run following command in your terminal to start with the up-to-date cli:

```
npm init ic@latest
```

Let me know if it works out.

**Comment by jacmos3** [comment]
Amazing. It solved. You are great!

**Comment by peterpeterparker** [comment]
Awesome, thanks for the feedback
